#!/usr/bin/fish

if test -z "$RCLONE_S3_ACCESS_KEY_ID" -o -z "$RCLONE_S3_SECRET_ACCESS_KEY"
  echo "Need AWS S3 credentials."
  exit 1
end

if test -z "$ARANGODB_ENDPOINT"
  echo Need ARANGODB_ENDPOINT in environment
  exit 2
end

set -xg RCLONE_S3_REGION us-west-2

rclone --progress copy s3://patents-data/patents_arangodb_naive.csv.xz .
rclone --progress copy s3://patents-data/patents_arangodb_smart.csv.xz .
rclone --progress copy s3://patents-data/citations_arangodb_naive.csv.xz .
rclone --progress copy s3://patents-data/citations_arangodb_smart.csv.xz .
