apiVersion: v1
kind: Pod
metadata:
  name: patentsimporter
spec:
  containers:
  - name: importer
    image: neunhoef/patentimport
    env:
    - name: RCLONE_S3_ACCESS_KEY_ID
      value: "ADD_YOURS_HERE"
    - name: RCLONE_S3_SECRET_ACCESS_KEY
      value: "ADD_YOURS_HERE"
    - name: ARANGODB_ENDPOINT
      value: "ssl://35.204.64.118:8529"
    - name: ARANGODB_USER
      value: "root"
    - name: ARANGODB_PASSWD
      value: ""
